### ISSUE TITLE
Additional Materials..?

### ISSUE THREAD

**Issue by peterprescott** [darribas/spoken_postcodes_rsrs#1]
"Currently a placeholder, additional materials will be added later."

Obviously this was five years ago, and so I doubt you still have them...

But I just came across your piece on [Spoken Postcodes](https://rsa.tandfonline.com/doi/full/10.1080/21681376.2015.1067151?scroll=top&needAccess=true#.XoSDYohKiUk) -- really interesting!

And I thought maybe it's worth saying that someone might have been interested in those additional materials :)

**Comment by darribas** [comment]
yes, this is a "work in progress...". What materials were you thinking? I have all the stuff still, but not everything can be published (e.g. raw Twitter data).

**Comment by peterprescott** [comment]
Wasn't thinking anything very specific, just interested in the idea, and when it said "The underlying research materials for this article can be accessed at github" I thought it would be fun to have a play :) I haven't done anything with Twitter data yet, but it's on my list...
